# Generated by Django 4.1.6 on 2023-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regionCd', models.IntegerField(blank=True, null=True)),
                ('regionNm', models.CharField(blank=True, max_length=200, null=True)),
                ('siDoNm', models.CharField(blank=True, max_length=10, null=True)),
                ('siGunGuNm', models.CharField(blank=True, max_length=10, null=True)),
                ('umdNm', models.CharField(blank=True, max_length=10, null=True)),
                ('riNm', models.CharField(blank=True, max_length=10, null=True)),
                ('siDoCd', models.IntegerField(blank=True, null=True)),
                ('siGunGuCd', models.IntegerField(blank=True, null=True)),
                ('DongCd', models.IntegerField(blank=True, null=True)),
                ('riCd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['regionCd'],
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longTermAdminCd', models.CharField(max_length=15)),
                ('longTermAdminNm', models.CharField(max_length=100)),
                ('adminPttnName', models.CharField(max_length=20)),
                ('ratingCd', models.CharField(max_length=15)),
                ('siDoName', models.CharField(blank=True, max_length=20, null=True)),
                ('siGunGuName', models.CharField(blank=True, max_length=20, null=True)),
                ('ratingDate', models.DateField(blank=True, null=True)),
                ('ratingGrade', models.CharField(blank=True, max_length=1, null=True)),
                ('opRating', models.IntegerField(blank=True, null=True)),
                ('safeRating', models.IntegerField(blank=True, null=True)),
                ('rightRating', models.IntegerField(blank=True, null=True)),
                ('processRating', models.IntegerField(blank=True, null=True)),
                ('resultRating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ratingDate'],
            },
        ),
    ]
