# Generated by Django 4.1.6 on 2023-02-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0008_alter_review_options_alter_review_modifydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='longTermAdminCd',
            new_name='care',
        ),
    ]
